# Generated by Django 3.2.7 on 2021-10-18 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=150, null=True)),
                ('earning', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20, null=True)),
                ('current_date', models.IntegerField(default=1)),
                ('state_finish', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.IntegerField(null=True)),
                ('team2', models.IntegerField(null=True)),
                ('day', models.IntegerField(default=1)),
                ('spring', models.CharField(max_length=20, null=True)),
                ('summer', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_num1', models.IntegerField(default=0)),
                ('team_num2', models.IntegerField(default=0)),
                ('match_num', models.IntegerField(default=0)),
                ('result', models.CharField(max_length=20, null=True)),
                ('league', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.league')),
            ],
        ),
        migrations.CreateModel(
            name='MyPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('feeling', models.IntegerField(default=0)),
                ('status1', models.IntegerField(default=0)),
                ('status2', models.IntegerField(default=0)),
                ('status3', models.IntegerField(default=0)),
                ('remain', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=150, null=True)),
                ('earning', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('year', models.IntegerField(default=0)),
                ('season', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blue', models.IntegerField(default=0)),
                ('red', models.IntegerField(default=0)),
                ('idx', models.IntegerField(default=1)),
                ('result', models.IntegerField(default=1)),
                ('match', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.match')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('season', models.CharField(max_length=20)),
                ('year', models.IntegerField(default=0)),
                ('position', models.CharField(max_length=20)),
                ('status1', models.IntegerField(default=0)),
                ('status2', models.IntegerField(default=0)),
                ('status3', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images')),
                ('team', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='MyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('money', models.IntegerField(default=0)),
                ('popularity', models.IntegerField(default=0)),
                ('adc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adc', to='api.myplayer')),
                ('enterprise1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enterprise1', to='api.enterprise')),
                ('enterprise2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enterprise2', to='api.enterprise')),
                ('jungle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='junggle', to='api.myplayer')),
                ('mid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mid', to='api.myplayer')),
                ('sponsor1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor1', to='api.sponsor')),
                ('sponsor2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor2', to='api.sponsor')),
                ('sponsor3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor3', to='api.sponsor')),
                ('sub1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub1', to='api.myplayer')),
                ('sub2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub2', to='api.myplayer')),
                ('support', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support', to='api.myplayer')),
                ('top', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top', to='api.myplayer')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='myplayer',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.player'),
        ),
        migrations.AddField(
            model_name='myplayer',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.schedule'),
        ),
        migrations.AddField(
            model_name='myplayer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LeagueTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.IntegerField(default=0)),
                ('lose', models.IntegerField(default=0)),
                ('team_num', models.IntegerField(default=0)),
                ('base_team', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.team')),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.league')),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='my_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.myteam'),
        ),
        migrations.AddField(
            model_name='league',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
