# Generated by Django 3.2.7 on 2021-09-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='image',
        ),
        migrations.AddField(
            model_name='player',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
