# Generated by Django 3.2.7 on 2021-09-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210927_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='season',
            field=models.CharField(max_length=20),
        ),
    ]
