# Generated by Django 3.2.7 on 2021-10-25 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_champion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='idx',
            new_name='match_num',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='blue',
            new_name='my_baron',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='red',
            new_name='my_dragon',
        ),
        migrations.AddField(
            model_name='match',
            name='status_finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='set',
            name='my_adc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_adc', to='api.champion'),
        ),
        migrations.AddField(
            model_name='set',
            name='my_gold',
            field=models.IntegerField(default=2500),
        ),
        migrations.AddField(
            model_name='set',
            name='my_jng',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_jng', to='api.champion'),
        ),
        migrations.AddField(
            model_name='set',
            name='my_mid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_mid', to='api.champion'),
        ),
        migrations.AddField(
            model_name='set',
            name='my_sup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_sup', to='api.champion'),
        ),
        migrations.AddField(
            model_name='set',
            name='my_top',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_top', to='api.champion'),
        ),
        migrations.AddField(
            model_name='set',
            name='my_tower1',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='set',
            name='my_tower2',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='set',
            name='my_tower3',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='set',
            name='my_tower4',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='set',
            name='my_tower5',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='set',
            name='my_tower6',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='set',
            name='my_tower7',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='set',
            name='my_tower8',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='set',
            name='my_tower9',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='set',
            name='my_tower_destroy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='set',
            name='op_adc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='op_adc', to='api.champion'),
        ),
        migrations.AddField(
            model_name='set',
            name='op_baron',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='set',
            name='op_dragon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='set',
            name='op_gold',
            field=models.IntegerField(default=2500),
        ),
        migrations.AddField(
            model_name='set',
            name='op_jng',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='op_jng', to='api.champion'),
        ),
        migrations.AddField(
            model_name='set',
            name='op_mid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='op_mid', to='api.champion'),
        ),
        migrations.AddField(
            model_name='set',
            name='op_sup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='op_sup', to='api.champion'),
        ),
        migrations.AddField(
            model_name='set',
            name='op_top',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='op_top', to='api.champion'),
        ),
        migrations.AddField(
            model_name='set',
            name='op_tower1',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='set',
            name='op_tower2',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='set',
            name='op_tower3',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='set',
            name='op_tower4',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='set',
            name='op_tower5',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='set',
            name='op_tower6',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='set',
            name='op_tower7',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='set',
            name='op_tower8',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='set',
            name='op_tower9',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='set',
            name='op_tower_destroy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='set',
            name='side',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_num',
            field=models.IntegerField(default=1),
        ),
    ]
