# Generated by Django 3.2.7 on 2021-10-25 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211025_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='match_num',
            new_name='set_num',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='match_num',
            new_name='set_num',
        ),
    ]
