# Generated by Django 3.2.7 on 2021-09-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_player_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='season',
            field=models.CharField(max_length=30),
        ),
    ]
