# Generated by Django 3.2.7 on 2021-10-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211025_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='status',
            field=models.CharField(default='bp', max_length=10),
        ),
    ]
