# Generated by Django 3.2.7 on 2021-10-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_set_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='turn',
            field=models.IntegerField(default=1),
        ),
    ]
