# Generated by Django 3.2.7 on 2021-10-01 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_player_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myteam',
            name='adc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adc', to='api.myplayer'),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='enterprise1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enterprise1', to='api.enterprise'),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='enterprise2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enterprise2', to='api.enterprise'),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='junggle',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='junggle', to='api.myplayer'),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='mid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mid', to='api.myplayer'),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='sponsor1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor1', to='api.sponsor'),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='sponsor2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor2', to='api.sponsor'),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='sponsor3',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor3', to='api.sponsor'),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='sub1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub1', to='api.myplayer'),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='sub2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub2', to='api.myplayer'),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='support',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support', to='api.myplayer'),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='top',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top', to='api.myplayer'),
        ),
    ]
