# Generated by Django 3.2.7 on 2021-11-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_match_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='is_baron',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='set',
            name='is_elder',
            field=models.IntegerField(default=0),
        ),
    ]
