# Generated by Django 3.2.7 on 2021-10-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_myteam_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myteam',
            old_name='junggle',
            new_name='jungle',
        ),
        migrations.AddField(
            model_name='myteam',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
