# Generated by Django 3.2.7 on 2021-10-04 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211004_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myplayer',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='myplayer',
            name='schedule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.schedule'),
        ),
    ]
