# Generated by Django 3.2.7 on 2021-11-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211104_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='league',
            name='win',
            field=models.IntegerField(default=0),
        ),
    ]
