# Generated by Django 3.2.7 on 2021-11-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211105_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='myplayer',
            name='exp',
            field=models.IntegerField(default=0),
        ),
    ]
