# Generated by Django 3.2.7 on 2021-10-05 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211004_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueteam',
            name='base_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.team'),
        ),
    ]
