# Generated by Django 3.2.7 on 2021-11-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211108_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
