# Generated by Django 3.2.7 on 2021-10-05 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_leagueteam_base_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueteam',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.league'),
        ),
    ]
