# Generated by Django 3.2.7 on 2021-10-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_leagueteam_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='season',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
