# Generated by Django 3.2.7 on 2021-11-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_champion_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='images',
            field=models.CharField(default='/ api/media/images/player.png', max_length=100),
        ),
    ]
