# Generated by Django 3.2.7 on 2021-10-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_league_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='current_date',
            field=models.IntegerField(default=1),
        ),
    ]
