# Generated by Django 3.2.7 on 2021-10-05 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_league_current_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.IntegerField(default=1)),
                ('team2', models.IntegerField(default=1)),
                ('day', models.IntegerField(default=1)),
                ('spring', models.CharField(max_length=20, null=True)),
                ('summer', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='league',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.league'),
        ),
    ]
